### PR TITLE
Add base manifests

### PR DESCRIPTION
**Pull request by cPu1**
Adds base manifests for Prometheus, Grafana, ALB Ingress controller and Metrics server.
https://github.com/weaveworks/aws-workstream/issues/24
https://github.com/weaveworks/aws-workstream/issues/25
https://github.com/weaveworks/aws-workstream/issues/26

### CODE REVIEW

**Comment by martina-if** [comment]
These are the spikes, can you link to the actual stories instead?

**Comment by martina-if** [comment]
@cPu1 Can you add the Go templating to these manifests?

**Comment by cPu1** [comment]
@martina-if yes, I will add templating for them.

**Comment by martina-if** [comment]
This Looks good to me. I think we should merge it and test it.

**Review by martina-if — APPROVED** [review]

**Pull request merged**
