### PR TITLE
add .wksctlignore file

### PR DESCRIPTION
**Pull request by chanwit**
add a blank .wksctlignore file to tell wksctl that it must ignores files from this directory when doing `wksctl profile enable`.

### CODE REVIEW

**Comment by chanwit** [comment]
kindly ping @stefanprodan @palemtnrider @mflendrich 
is it ok to implement this idea?

**Comment by palemtnrider** [comment]
Hi @chanwit I don't see where weaveworks/wksctl might be checking for this file.  Is that going to be added later?

**Comment by chanwit** [comment]
@palemtnrider I'm working on it. Feedback from @stefanprodan that I should use something similar to `.gitignore`.

**Comment by chanwit** [comment]
Here's the implementation to recognize `.wksctlignore` in `wksctl profile enable`.

https://github.com/weaveworks/wksctl/pull/104

**Comment by martina-if** [comment]
@chanwit Sorry for the very late reply, we haven't been watching this repo.

 I think this repo doesn't know anything about `wksctl` so it doesn't make sense to add a file here for that. Instead that file should be created by wks or other tooling that may connect them.

**Pull request closed without merging**
